version: '3'
services:
  dbt-bq-dtc:
    build:
      context: docker_setup/.
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - ./bq_taxi_trips:/usr/app
      - ~/.dbt/:/root/.dbt/
      - ~/Documents/secrets/personal-gcp.json:/.google/credentials/google_credentials.json
    network_mode: host